#!/bin/sh

# Package
PACKAGE="consul"
DNAME="consul"

PACKAGE_DIR="/var/packages/${DNAME}"
SSS="/var/packages/${DNAME}/scripts/start-stop-status"

SERVICETOOL="/usr/syno/bin/servicetool"
FWPORTS="/var/packages/${DNAME}/scripts/${PACKAGE}.sc"

LOG_FILE="/var/log/consul.log"

CONF_DIR="${PACKAGE_DIR}/conf"

BACKUP_DIR="/tmp/consul_backup"

preinst ()
{
    if [ -d "${CONF_DIR}" ]; then
        mkdir "${BACKUP_DIR}"
        cp -r "${CONF_DIR}/" "${BACKUP_DIR}/"
    fi

    exit 0
}

postinst ()
{
    # Add firewall config
    ${SERVICETOOL} --install-configure-file --package ${FWPORTS} >> /dev/null

    exit 0
}

preuninst ()
{
    # Stop the package
    ${SSS} stop > /dev/null

    # Remove firewall config
    if [ "${SYNOPKG_PKG_STATUS}" == "UNINSTALL" ]; then
        ${SERVICETOOL} --remove-configure-file --package ${PACKAGE}.sc >> /dev/null
    fi

    exit 0
}

postuninst ()
{
    # remove log file
    rm -f ${LOG_FILE}

    rm -R "${BACKUP_DIR}"
    exit 0
}

preupgrade ()
{
    # Stop the package
    ${SSS} stop > /dev/null

    if [[ ! -d "${BACKUP_DIR}" ]]; then
        mkdir "${BACKUP_DIR}"
    fi

    exit 0
}

postupgrade ()
{
    exit 0
}
