#!/bin/sh
#

# Package
PACKAGE="consul"
DNAME="consul"

# Others

ROOT_DIR="/var/packages/consul"
CONF_DIR="${ROOT_DIR}/etc"
VAR_DIR="${ROOT_DIR}/var"

CONSUL="/usr/local/bin/consul"
PID_FILE="${VAR_DIR}/consul.pid"
LOG_FILE="${VAR_DIR}/consul.log"


ARGS="agent -config-dir=${CONF_DIR} -data-dir=${VAR_DIR}/data"

export HOME="${ROOT_DIR}/home"
export USER=consul
export USERNAME=consul

start_daemon ()
{
    echo "Using configuration file in ${CONF_DIR}" >> $LOG_FILE
    ipfound=0
    while ip -f inet addr show dev eth0 | grep -Po 'inet 192.168' > /dev/null; do
      echo "waiting for IP address" >> $LOG_FILE
      sleep 1
    done

    ifconfig >> $LOG_FILE
    ${CONSUL} $ARGS >> ${LOG_FILE} 2>&1 &
    echo $! > ${PID_FILE}
}

stop_daemon ()
{
    kill `cat ${PID_FILE}`
    wait_for_status 1 20 || kill -9 `cat ${PID_FILE}`
    rm -f ${PID_FILE}
}

daemon_status ()
{
    if [ -f ${PID_FILE} ] && kill -0 `cat ${PID_FILE}` > /dev/null 2>&1; then
        return
    fi
    rm -f ${PID_FILE}
    return 1
}

wait_for_status ()
{
    counter=$2
    while [ ${counter} -gt 0 ]; do
        daemon_status
        [ $? -eq $1 ] && return
        let counter=counter-1
        sleep 1
    done
    return 1
}


case $1 in
    start)
        if daemon_status; then
            echo ${DNAME} is already running
        else
            echo Starting ${DNAME} ...
            start_daemon
        fi
        ;;
    stop)
        if daemon_status; then
            echo Stopping ${DNAME} ...
            stop_daemon
        else
            echo ${DNAME} is not running
        fi
        ;;
    restart)
        stop_daemon
        start_daemon
        ;;
    status)
        if daemon_status; then
            echo ${DNAME} is running
            exit 0
        else
            echo ${DNAME} is not running
            exit 1
        fi
        ;;
    log)
        echo ${LOG_FILE}
        ;;
    *)
        exit 1
        ;;
esac
